/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh;
    bottom: THREE.Mesh;
    bottom_emissive: THREE.Mesh;
    chest: THREE.Mesh;
    chest_emissive: THREE.Mesh;
    hand_left: THREE.Mesh;
    hand_right: THREE.Mesh;
    neck: THREE.Mesh;
    neck_emissive: THREE.Mesh;
    head: THREE.Mesh;
    antenna_left_emissive: THREE.Mesh;
    antenna_right_emissive: THREE.Mesh;
    ear_left_emissive: THREE.Mesh;
    ear_right_emissive: THREE.Mesh;
    ears: THREE.Mesh;
    face_visor: THREE.Mesh;
    eyes: THREE.Mesh;
    mouth: THREE.Mesh;
  };
  materials: {
    White_Glossy: THREE.MeshPhysicalMaterial;
    Blue_Light: THREE.MeshStandardMaterial;
    Black_Matt: THREE.MeshPhysicalMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/robot.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="origin">
          <mesh
            name="body"
            castShadow
            receiveShadow
            geometry={nodes.body.geometry}
            material={materials.White_Glossy}
          >
            <mesh
              name="bottom"
              castShadow
              receiveShadow
              geometry={nodes.bottom.geometry}
              material={materials.White_Glossy}
            >
              <mesh
                name="bottom_emissive"
                castShadow
                receiveShadow
                geometry={nodes.bottom_emissive.geometry}
                material={materials.Blue_Light}
              />
            </mesh>
            <mesh
              name="chest"
              castShadow
              receiveShadow
              geometry={nodes.chest.geometry}
              material={materials.White_Glossy}
            >
              <mesh
                name="chest_emissive"
                castShadow
                receiveShadow
                geometry={nodes.chest_emissive.geometry}
                material={materials.Blue_Light}
              />
            </mesh>
            <group name="hand_left_pivot" position={[0.363, 0.932, 0]}>
              <mesh
                name="hand_left"
                castShadow
                receiveShadow
                geometry={nodes.hand_left.geometry}
                material={materials.White_Glossy}
                position={[-0.363, -0.932, 0]}
              />
            </group>
            <group name="hand_right_pivot" position={[-0.363, 0.932, 0]}>
              <mesh
                name="hand_right"
                castShadow
                receiveShadow
                geometry={nodes.hand_right.geometry}
                material={materials.White_Glossy}
                position={[0.363, -0.932, 0]}
              />
            </group>
            <mesh
              name="neck"
              castShadow
              receiveShadow
              geometry={nodes.neck.geometry}
              material={materials.White_Glossy}
            >
              <mesh
                name="neck_emissive"
                castShadow
                receiveShadow
                geometry={nodes.neck_emissive.geometry}
                material={materials.Blue_Light}
              />
            </mesh>
          </mesh>
          <group name="head_pivot" position={[0, 1.384, -0.042]}>
            <mesh
              name="head"
              castShadow
              receiveShadow
              geometry={nodes.head.geometry}
              material={materials.White_Glossy}
            >
              <mesh
                name="antenna_left_emissive"
                castShadow
                receiveShadow
                geometry={nodes.antenna_left_emissive.geometry}
                material={materials.Blue_Light}
                position={[0, -1.384, 0.042]}
              />
              <mesh
                name="antenna_right_emissive"
                castShadow
                receiveShadow
                geometry={nodes.antenna_right_emissive.geometry}
                material={materials.Blue_Light}
                position={[0, -1.384, 0.042]}
              />
              <mesh
                name="ear_left_emissive"
                castShadow
                receiveShadow
                geometry={nodes.ear_left_emissive.geometry}
                material={materials.Blue_Light}
                position={[0, -1.384, 0.042]}
              />
              <mesh
                name="ear_right_emissive"
                castShadow
                receiveShadow
                geometry={nodes.ear_right_emissive.geometry}
                material={materials.Blue_Light}
                position={[0, -1.384, 0.042]}
              />
              <mesh
                name="ears"
                castShadow
                receiveShadow
                geometry={nodes.ears.geometry}
                material={materials.Black_Matt}
                position={[0, -1.384, 0.042]}
              />
              <mesh
                name="face_visor"
                castShadow
                receiveShadow
                geometry={nodes.face_visor.geometry}
                material={materials.Black_Matt}
                position={[0, -1.384, 0.042]}
              >
                <mesh
                  name="eyes"
                  castShadow
                  receiveShadow
                  geometry={nodes.eyes.geometry}
                  material={materials.Blue_Light}
                />
                <mesh
                  name="mouth"
                  castShadow
                  receiveShadow
                  geometry={nodes.mouth.geometry}
                  material={materials.Blue_Light}
                />
              </mesh>
            </mesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robot.glb");
