services:
  - type: web
    name: block-shooter
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "9208"
      - key: NODE_ENV
        value: "production"
